<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <MicrosoftPackagesVersion>10.0.12</MicrosoftPackagesVersion>
    <Version>1.0.0</Version>

    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
  </PropertyGroup>
</Project>